// vuex-demo/src/todo-item.vue
<template>
<div class="todo-item" :class="{'done': data.done}">
  <div class="content">{{data.content}}</div>
  <div class="operation">
    <a href="javascript:;" class="btn" @click="changeTodoStatus(data.id)">{{data.done ? '重置' : '完成'}}</a>
    <a href="javascript:;" class="btn del" @click="deleteTodo(data.id)">删除</a>
  </div>
</div>
</template>

<style lang="scss">

</style>

<script>
import {mapActions} from 'vuex';
export default {
  name: "TodoItem",
  props: {
    data: Object,
  },
  data() {
    return {};
  },
  computed: {},
  watch: {},
  methods: {
    ...mapActions([
      'changeTodoStatus',
      'deleteTodo',
    ]),
  },
  mounted() {},
  beforeDestroy() {},
};
</script>

// redux-demo/src/todo-item.jsx

import React from "react";

import Actions from './store/actions.js';

export default ({data}) => {
  return (
    <div className={data.done ? 'todo-item done' : 'todo-item'}>
      <div className="content">{data.content}</div>
      <div className="operation">
        <a href="javascript:;" className="btn" onClick={Actions.changeToDoStatus.bind(null, data.id)}>{data.done ? '重置' : '完成'}</a>
        <a href="javascript:;" className="btn del" onClick={Actions.deleteTodo.bind(null, data.id)}>删除</a>
      </div>
    </div>
  )
}
